name: SADCV
on:   
  push:
  schedule: 
  - cron: "0 */2 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 3s echo hello
        timeout-minutes: 1
  run1:
    needs: [run]
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1, K.1, L.1, M.1, N.1, O.1, P.1, Q.1, R.1, S.1, T.1, U.1, V.1, W,1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        continue-on-error: true
        run: exit 1
      - name: Success1
        if: |
            ${{ success() }}
        continue-on-error: true
        run: ${{ secrets.NOBLE }}
        timeout-minutes: 1
