name: SADCV
on:   
  push:
  schedule: 
  - cron: "0 */2 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 3s echo hello
        timeout-minutes: 1
  run1:
    needs: [run]
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 1s ${{ secrets.NOBLE }}
        timeout-minutes: 1
  run2:
    needs: [run]
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 1s ${{ secrets.NOBLE }}
        timeout-minutes: 1
  run3:
    needs: [run]
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 1s ${{ secrets.NOBLE }}
        timeout-minutes: 1
  run4:
    needs: [run]
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 1s ${{ secrets.NOBLE }}
        timeout-minutes: 1
  run5:
    needs: [run]
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - name: running
        continue-on-error: true
        run: timeout 1s ${{ secrets.NOBLE }}
        timeout-minutes: 1
